apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://gitlab.com/biletado/kustomize.git//overlays/kind?ref=main

patches:
  - target:
      kind: Deployment
      name: assets
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/lucaamueller/webeng2_abgabe_luca_jan:latest
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8080 # Ändere dies, falls dein Container einen anderen Port verwendet
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

namespace: biletado
