name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: assets_v3

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/assets_v3
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_SECURITY_ENABLED: false

    steps:
      # 1. Code aus dem Repository holen
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. JDK f端r Spring Boot einrichten
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Maven Build ausf端hren
      - name: Build Project with Maven
        run: ./mvnw clean package -DskipTests=true

      # 4. Maven Tests ausf端hren (optional)
      - name: Run Tests
        run: ./mvnw test

      # 5. Deployment-Schritt (Beispiel f端r SSH-Zugriff auf einen Server)
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd /path/to/deployment
            rm -rf *
            cp /path/to/built-jar/application.jar .
            java -jar application.jar
